CREATE DATABASE APRS;
USE APRS;

CREATE TABLE APRSPosits
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ReportTime DATETIME NOT NULL,
CallsignSSID VARCHAR(9) NOT NULL,
Latitude FLOAT(10,6) NOT NULL,
Longitude FLOAT(10,6) NOT NULL,
Altitude INT,
Speed INT,
Course SMALLINT,
Icon CHAR(2),
Comment BLOB,
Packet BLOB
);

CREATE USER APRS_user@localhost IDENTIFIED BY 'password';
GRANT ALL ON APRS.* TO APRS_user;
FLUSH PRIVILEGES;